---
output: html_document
editor_options: 
  chunk_output_type: console
---


Now we are going to work with BAMM

```{r}
library(BAMMtools)
library(coda)

## load data
mytree <- read.tree("tree.tree")
mcmcout <- read.csv("mcmc_out.txt")

## create edata
edata <- getEventData(mytree, eventdata = "event_data.txt", burnin=0.15)


#### Check convergence
plot(mcmcout$logLik ~ mcmcout$generation)

burnstart <- floor(0.15 * nrow(mcmcout))
postburn <- mcmcout[burnstart:nrow(mcmcout), ]

effectiveSize(postburn$N_shifts)
effectiveSize(postburn$logLik)



### Shift probabilities
shift_probs <- summary(edata)
shift_probs


### Bayes factors
bfmat <- computeBayesFactors(postburn, expectedNumberOfShifts=1, burnin=0.15)
bfmat

#### PLOT CREDIBLE SHIFTS
css <- credibleShiftSet(edata, expectedNumberOfShifts=1, threshold=5, set.limit = 0.95)
css
plot.credibleshiftset(css,spex = "netdiv")


### PLOT BEST SHIFT
par(mfrow=c(1,1))
best <- getBestShiftConfiguration(edata, expectedNumberOfShifts=1)
best
plot.bammdata(best, lwd = 2,spex = "netdiv",label=T,cex=0.5)
axisPhylo()
addBAMMshifts(best, cex=3)
best$eventData

### RATE through time
st <- max(branching.times(mytree))
plotRateThroughTime(edata, intervalCol="red", avgCol="red", start.time=st, ylim=c(0,0.2), cex.axis=1,ratetype='netdiv')



```


BISSE

```{r}

library(ape)
mydata <- read.csv ("Final4.csv")

setdiff(mydata$Nombres, mytree$tip.label)
setdiff(mytree$tip.label,mydata$Nombres)

mytree2 <- drop.tip(mytree,c("L_syriacum", "L_velutinum", "L_cariense", "L_oligophyllum", "L_meletonis", "L_bungei",    "L_unguiculatum", "L_olympicum"  ))

setdiff(mydata$Nombres, mytree2$tip.label)
setdiff(mytree2$tip.label,mydata$Nombres)

write.tree(mytree2, file = "mytree.tree")


#############
mydata <- read.csv ("Final4.csv")
mytree2 <- read.tree("mytree.tree") 
states <- mydata$Pol2
names(states) <- mydata$Nombres
phy<-mytree2
library(diversitree)

#MARKOV
lik.mk2 <- make.mk2(phy, states)
fit.mk2 <- find.mle(lik.mk2, c(.1, .1), method="subplex")
coef(fit.mk2)

lik.mk1 <- constrain(lik.mk2, q10 ~ q01)
fit.mk1 <- find.mle(lik.mk1, .1, method="subplex")
anova(fit.mk2, mk1=fit.mk1)

plot(phy, show.tip.label=FALSE, no.margin=TRUE)
col <- c("#004165", "#eaab00")
tiplabels(col=col[states+1], pch=19, adj=1)
nodelabels(col=col[attr(states, "node.state")+1], pch=19)
st <- asr.marginal(lik.mk1 , coef(fit.mk1))
nodelabels(pie=t(st), piecol=col, cex=.5)


prior.exp <- make.prior.exponential(10)
set.seed(1)
samples <- mcmc(lik.mk2, c(.1, .1), nsteps=5000, prior=prior.exp,w=.1, print.every=0)
samples <- subset(samples, i > 500)
mean(samples$q01 > samples$q10)
col <- c("#004165", "#eaab00")
profiles.plot(samples[c("q01", "q10")], col.line=col, las=1,legend.pos="topright")

#BISSE
sampling.f <- 0.6
lik <- make.bisse(phy, states, sampling.f=sampling.f)
pars <- c(0.1, 0.2, 0.03, 0.03, 0.01, 0.01)
lik(pars) 
p <- starting.point.bisse(phy)
p
fit <- find.mle(lik, p)
fit$lnLik
round(coef(fit), 3)

plot(phy, show.tip.label=FALSE, no.margin=TRUE)
col <- c("#004165", "#eaab00")
tiplabels(col=col[states+1], pch=19, adj=1)
st <- asr.marginal(lik, coef(fit))
nodelabels(pie=t(st), piecol=col, cex=.5)


lik.l <- constrain(lik, lambda1 ~ lambda0)
fit.l <- find.mle(lik.l, p[argnames(lik.l)])
fit.l$lnLik
round(rbind(full=coef(fit), equal.l=coef(fit.l, TRUE)), 3)
anova(fit, equal.l=fit.l)

lik.q <- constrain(lik, q01 ~ q10)
fit.q <- find.mle(lik.q, p[argnames(lik.q)])
fit.q$lnLik

round(rbind(full=coef(fit), equal.l=coef(fit.l, TRUE), equal.q=coef(fit.q, TRUE)), 3)
anova(fit, equal.l=fit.l, equal.q=fit.q)

lik.m <- constrain(lik, mu1 ~ mu0)
fit.m <- find.mle(lik.m, p[argnames(lik.m)])
fit.m$lnLik
round(rbind(full=coef(fit), equal.l=coef(fit.l, TRUE), equal.q=coef(fit.q, TRUE), equal.m=coef(fit.m, TRUE)), 3)
anova(fit, equal.l=fit.l, equal.q=fit.q, equal.m = fit.m)


prior <- make.prior.exponential(1 / (2 * (p[1] - p[3])))
set.seed(1)
tmp <- mcmc(lik, fit$par, nsteps=100, prior=prior,lower=0, w=rep(1, 6), print.every=0)
w <- diff(sapply(tmp[2:7], range))
w
samples <- mcmc(lik, fit$par, nsteps=1000000, w=w, lower=0, prior=prior,print.every=1000)

load(file = "./run1/samples.RData")

par(mfrow=c(1,1), mar=c(3, 4, 0, 1))
col <- c("red", "orange", "blue", "purple", "black", "gray")
profiles.plot(samples[c("lambda0", "lambda1", "mu0", "mu1", "q01", "q10")], col.line=col, las=1, n.br=1000, xlab="Speciation, extinction and transition rate", legend="topright")

col <- c("red", "orange")
profiles.plot(samples[c("lambda0", "lambda1")], col.line=col, las=1, n.br=1000, xlab="Speciation rate", legend="topright")

col <- c("blue", "purple")
profiles.plot(samples[c("mu0", "mu1")], col.line=col, las=1, n.br=1000,xlab="Extinction rate", legend="topright")

col <- c("black", "gray")
profiles.plot(samples[c("q01", "q10")], col.line=col, las=1, n.br=1000, xlab="Transition rate", legend="topright")  

col <- c("green", "yellow")
samples$diversification0 <- samples$lambda0 - samples$mu0 
samples$diversification1 <- samples$lambda1 - samples$mu1 
profiles.plot(samples[c("diversification0", "diversification1")], col.line=col, las=1, n.br=1000, xlab="Diversification rate", legend="topright")

mean(samples$q01 > samples$q10)
mean(samples$mu0 > samples$mu1)
mean(samples$lambda0 > samples$lambda1)
mean(samples$diversification0 > samples$diversification1)

```


GEOSSE

```{r}
library(diversitree)

phy <- read.tree("tree.tree")
mydata2 <- read.csv ("mydata.csv")
states <- as.character(mydata2$Species)
names(states) <- mydata2$Area
setdiff(phy$tip.label, states)
setdiff(states,phy$tip.label)
phy$tip.state <- names(states)[match(phy$tip.label,states)]
names(phy$tip.state) <- states[match(phy$tip.label,states)] 

statecols <- c("AB"="purple", "A"="blue", "B"="red")
plot(phy, tip.color=statecols[phy$tip.state], cex=0.5)

p <- starting.point.geosse(phy)
p

phy$tip.state[phy$tip.state == "A"] <- 1
phy$tip.state[phy$tip.state == "B"] <- 2
phy$tip.state[phy$tip.state == "AB"] <- 0
phy$tip.state <- as.numeric(phy$tip.state)
names(phy$tip.state) <- states[match(phy$tip.label,states)] 

lik1 <- make.geosse(phy, phy$tip.state, sampling.f = c(0.6,0.6,0.6))
lik2 <- constrain(lik1, sAB ~ 0)
lik3 <- constrain(lik1, sA ~ sB, xA ~ xB)

ml1 <- find.mle(lik1, p)
p <- coef(ml1)
ml2 <- find.mle(lik2, p[argnames(lik2)])
ml3 <- find.mle(lik3, p[argnames(lik3)])

round(rbind(full = coef(ml1),no.sAB = coef(ml2, TRUE),eq.div = coef(ml3, TRUE)), 3)

anova(ml1, no.sAB = ml2, eq.div = ml3)



p <- coef(ml2)
prior <- make.prior.exponential(1/2)

set.seed(1)
tmp <- mcmc(lik2, p, nsteps=100, prior=prior, w=1, print.every=0)
w <- diff(sapply(tmp[2:7], quantile, c(0.025, 0.975)))

mcmc2 <- mcmc(lik2, p, nsteps=1000000, prior=prior, w=w)

load(file = "./run2/samples2.RData")

mcmc2diff <- with(mcmc2, data.frame(s.diff=sA-sB,x.diff=xA-xB,d.diff=dA-dB,div.A=sA-xA,div.B=sB-xB))
colMeans(mcmc2diff > 0)
col1 <- c("red", "orange", "blue", "purple", "black", "gray")
col2 <- col1[c(1,3,5)]
mcmc2diff <- with(mcmc2, data.frame(s.diff=sA-sB, x.diff=xA-xB, d.diff=dA-dB))
par(mfrow=c(2,1), mar=c(3, 4, 0, 1))
profiles.plot(mcmc2[2:7], col.line=col1, n.br=1000, xlab="", ylab="")
legend("topright", argnames(lik2), col=col1, lty=1, cex = 0.5)
profiles.plot(mcmc2diff, col.line=col2, n.br=1000, xlab="", ylab="")
legend("topright", colnames(mcmc2diff), col=col2, lty=1, cex = 0.5)
title(xlab="rate", ylab="posterior probability density", outer=T, line=-1)


par(mfrow=c(1,1), mar=c(3, 4, 0, 1))
col <- c("red", "orange", "blue", "purple", "black", "gray")
profiles.plot(mcmc2[c("sA", "sB", "xA", "xB", "dA", "dB")], col.line=col, las=1, n.br=1000, xlab="Speciation, extinction and dispersal rate", legend="topright")

col <- c("red", "orange")
profiles.plot(mcmc2[c("sA", "sB")], col.line=col, las=1, n.br=1000, xlab="Speciation rate", legend="topright")

col <- c("blue", "purple")
profiles.plot(mcmc2[c("xA", "xB")], col.line=col, las=1, n.br=1000,xlab="Extinction rate", legend="topright")

col <- c("black", "gray")
profiles.plot(mcmc2[c("dA", "dB")], col.line=col, las=1, n.br=1000, xlab="Dispersal rate", legend="topright")  

col <- c("green", "yellow")
mcmc2$diversificationA <- mcmc2$sA - mcmc2$xA 
mcmc2$diversificationB <- mcmc2$sB - mcmc2$xB
profiles.plot(mcmc2[c("diversificationA", "diversificationB")], col.line=col, las=1, n.br=1000, xlab="Diversification rate", legend="topright")

mean(mcmc2$dA > mcmc2$dB)
mean(mcmc2$xA > mcmc2$xB)
mean(mcmc2$sA > mcmc2$sB)
mean(mcmc2$diversificationA > mcmc2$diversificationB)


```

